### ISSUE TITLE
添加域名的时候没有去掉首尾的空格

### ISSUE THREAD

**Issue by wangshijun** [blocklet/certificates-manager#13]
这样会导致创建证书、验证 dns 解析的时候出错，并且无法删除

https://18-180-145-193.ip.abtnet.io/admin/certificates-manager/adminUrl/?__bv__=0.2.13&__blang__=en

**Comment by polunzh** [comment]
fixed: https://github.com/blocklet/certificates-manager/commit/ccb987597d0d9167606061f014b2f88c8e5a11a7
